//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.07 at 05:03:57 PM EET 
//


package quoteutils;


import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;

import quoteutils.orm.LangConverter;


/**
 * <p>Java class for Quote complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Quote">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="id" use="required" type="{http://www.example.org/quote}QuoteId" />
 *       &lt;attribute name="lang" use="required" type="{http://www.example.org/quote}Lang" />
 *       &lt;attribute name="person" use="required" type="{http://www.example.org/quote}QuotePerson" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@Entity
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Quote", propOrder = {
    "text"
})
public class Quote {
	
    @XmlValue
    @Pattern(regexp="[а-яА-Яa-zA-Z0-9 :;,\\.\\-\"'\\!\\?\\s]{10,}", message="Quote must be 10 and more characters long. Only letters(Latin and Cyrillic), digits, period, colon, semicolon, comma, "  
			+ "double quote, question mark, exclamation mark and dash allowed in quote text.")
    protected String text = "";
    
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    
    @XmlAttribute(name = "id", required = true)
    protected int id;
     
    @Convert(converter=LangConverter.class)
    @NotNull(message="Language is required.")
    @XmlAttribute(name = "lang", required = true)
    protected Lang lang;
    
    @Pattern(regexp="[а-яА-Яa-zA-Z 0-9\\-']{3,}", message="Person name must be 3 and more characters long. Only letters(Latin and Cyrillic), digits, "
    			+ "dash and single quote allowed in person field.")
    @XmlAttribute(name = "person", required = true)
    protected String person = "";
    
    @NotNull(message="User is required.")
    @XmlAttribute(name = "user", required = true)
    protected String user = "";
    
    public Quote(String text, String person, Lang lang, String username){
    	this.text = text;
    	this.person = person;
    	this.lang = lang;
    	this.user = username;
    }
    
    public Quote(){}

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link Lang }
     *     
     */
    public Lang getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lang }
     *     
     */
    public void setLang(Lang value) {
        this.lang = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerson(String value) {
        this.person = value;
    }
    
    public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}
    
    @Override
    public boolean equals(Object obj){
		return this.getText().equals(((Quote) obj).getText());
    }
    
    @Override
    public int hashCode(){
    	return this.getText().hashCode();
    }
    
    @Override
    public String toString(){
    	StringBuilder sb = new StringBuilder();
    	sb.append("Text: " + this.text + "\n");
    	sb.append("Person: " + this.person + "\n");
    	sb.append("Lang: " + this.lang.value() + "\n");
    	sb.append("User: " + this.user + "\n");
    	return sb.toString();
    }

}
