//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 01:42:52 PM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/user", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package userutils;
