//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 11:06:45 AM EEST 
//


package quoteutils.templateutils;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;

import quoteutils.Lang;


/**
 * <p>Java class for XmlQuote complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlQuote">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="lang" use="required" type="{http://localhost:5000/webapp}Lang" />
 *       &lt;attribute name="person" use="required" type="{http://localhost:5000/webapp}QuotePerson" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xmlQuote", propOrder = {
    "text"
})
public class XmlQuote {
	
	@Pattern(regexp="[а-яА-Яa-zA-Z0-9 :;,\\.\\-\"'\\!\\?\\s]{10,}", message="Quote must be 10 and more characters long. Only letters(Latin and Cyrillic), digits, period, colon, semicolon, comma, "  
			+ "double quote, question mark, exclamation mark and dash allowed in quote text.")
    @XmlValue
    protected String text = "";
    
	@NotNull
    @XmlAttribute(name = "lang", required = true)
    protected Lang lang;
    
	@Pattern(regexp="[а-яА-Яa-zA-Z 0-9\\-']{3,}", message="Person name must be 3 and more characters long. Only letters(Latin and Cyrillic), digits, "
			+ "dash and single quote allowed in person field.")
    @XmlAttribute(name = "person", required = true)
    protected String person = "";

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link Lang }
     *     
     */
    public Lang getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lang }
     *     
     */
    public void setLang(Lang value) {
        this.lang = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerson(String value) {
        this.person = value;
    }
    
    @Override
    public boolean equals(Object obj){
		return this.getText().equals(((XmlQuote) obj).getText());
    }
    
    @Override
    public int hashCode(){
    	return this.getText().hashCode();
    }

}
